### PR TITLE
Fixes MREs

### PR DESCRIPTION
**Pull request by Alterist**
Adds a Important part of the marine diet which was previously missing to MREs
untitled-1

### CODE REVIEW

**Comment by Alterist** [comment]
We need to have equal representation of the dietary requirements of all squads, favoring one squad over another is a massive imbalance, and should be something we strive for as we continue to create tasty food items for marines.

**Comment by Rohesie** [comment]
Look, we aim for a 75% delta liver intoxication rate because imperfect balance is part of our game design.

That said, crayons of each squad color would be nicer.

**Comment by Alterist** [comment]
So, what youre saying is....MOAR CRAYONS...

**Comment by Rohesie** [comment]
Always.

**Comment by Qustinnus** [comment]
fix the conflicts and its good

**Pull request closed without merging**
