### PR TITLE
Explosive Pouch Added to Marine/SL/Spec Vendors

### PR DESCRIPTION
**Pull request by Surrealaser**
Per title.

### CODE REVIEW

**Comment by carlarc** [comment]
im against putting it in the SL vendor since it kinda baits newbie sls to get an explosive pouch instead of a large general pouch which has the same storage space.
maybe make the pouch store 4 grenades? it seems kinda weird to me rn, just enough storage to be almost but not really worth it

**Comment by Rohesie** [comment]
The problem is balancing on how many rockets in comparison with nades you'll store. Because rockets are much more valuable.

**Comment by Surrealaser** [comment]
@Rohesie tbh I don't think it would be problematic to increase the capacity by +1

**Comment by Rohesie** [comment]
Go for it then.

**Pull request merged**
