### PR TITLE
Slow Stacking Removed for Staggerstun

### PR DESCRIPTION
**Pull request by Surrealaser**
Per title.

While a Xeno has slowdown stacks, it cannot receive additional slowdown stacks from the staggerstun effect most prominently featured on slugs.

### CODE REVIEW

**Comment by Rohesie** [comment]
Slowdown may come from more than one source in the long run, such as pulling humans and whatever else. Because we don't want effects to directly modify the speed var, just the modifier var. This means that if a xeno chooses to lose speed, like with the defender's head crest, even of only a little, they will be immune to the potentially larger slug slowdown.

**Comment by Surrealaser** [comment]
> Slowdown may come from more than one source in the long run, such as pulling humans and whatever else. Because we don't want effects to directly modify the speed var, just the modifier var. This means that if a xeno chooses to lose speed, like with the defender's head crest, even of only a little, they will be immune to the potentially larger slug slowdown.

Well the alternative is that we add a separate variable for the stagger slowdown.

**Comment by Rohesie** [comment]
Dependent on #417

**Comment by Surrealaser** [comment]
@Rohesie Flag might work for slowed as there is no way to alter the duration, so you can add a spawn timed removal or a world time stamp that gets compared during the life process which syncs with it, but it's crude and kludgy.

I have no plans to preclude stacking for staggered though.

**Comment by Rohesie** [comment]
Let's get the opinion of @ninjanomnom or @Qustinnus here.

**Comment by ninjanomnom** [comment]
We actualy have a fairly recent system in tg for managing speed sources and the like. That would be ideal if you wanted to port it. This system is acceptable though.

**Comment by Rohesie** [comment]
Conflicts.

**Pull request closed without merging**
