### PR TITLE
Lessens the DMCA on the Xeno Queen

### PR DESCRIPTION
**Pull request by Kerbin-Fiber**
Changes the CM Xeno Queen sprites to the TG sprites.

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
when can we expect to get icon diff bot :(

**Comment by F-OS** [comment]
[https://www.youtube.com/watch?v=ve9BdBOCohI](Related Song)

**Comment by Wilchenx** [comment]
@Kerbin-Fiber did you get ovipositor related sprites?

**Comment by Kerbin-Fiber** [comment]
Fuck

**Comment by Borisvanmemes** [comment]
The CM queen spites are way better then the /tg/ queen spites tbh, also yeah ovipositor

**Comment by Kerbin-Fiber** [comment]
Just gonna close this until I have time to work on the Ovi sprites and commit them

**Comment by MrStonedOne** [comment]
Re-open to test icondiffbot

**Comment by Kerbin-Fiber** [comment]
I might have enough done to commit some more things by tomorrow so we'll see if the Icondiff bot works then.

**Comment by MrAlphonzo** [comment]
THE PEOPLE DEMAND THE XENOMAID QUEEN SPRITE

**Comment by Kerbin-Fiber** [comment]
pfffffffffffffffffffffffffffffffffffffffffffff

**Comment by Kerbin-Fiber** [comment]
I'm losing time for this but if someone else would like to take this up, I can give you the files

**Comment by Kerbin-Fiber** [comment]
as if I were to continue working on this it'd take forever

**Comment by Kerbin-Fiber** [comment]
or I can not be stupid and update this to my latest work so anon can take this straight from the pr

**Comment by Kerbin-Fiber** [comment]
AH I SEE GOODBYE

**Pull request closed without merging**
