### PR TITLE
Spec armor no longer does negative damage

### PR DESCRIPTION
**Pull request by F-OS**
what the fuck CM

### CODE REVIEW

**Comment by Rohesie** [comment]
This is not a % reduction. If you want to understand how armor works check these:
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/blob/5f44f28548cdadaa9748fd8291b49dd30198ccd8/code/modules/mob/living/carbon/human/human_defense.dm
(specifically the `getarmor_organ` proc)
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/blob/master/code/modules/projectiles/updated_projectiles/projectile.dm
(the `human/bullet_act` proc)

**Comment by F-OS** [comment]
I know, i was just joking about the 105%, and considering that only admin spawned deathsquad helmets have more bullet resistance then this, i think it can be safely tuned down.

**Comment by Rohesie** [comment]
Sorry, I kind of don't see the need for this change. It's not as if we want the B18 to be a little more vulnerable to bullets in the head, even if only a tiny bit.

**Comment by F-OS** [comment]
Good point.

**Pull request closed without merging**
