### PR TITLE
deletes looc

### PR DESCRIPTION
**Pull request by LetterN**
and removes the anti-spam shit

### CODE REVIEW

**Comment by ninjanomnom** [comment]
Just remove looc honestly

**Comment by LetterN** [comment]
it's needed for not breaking immursion by using ((this)) shit type of looc

**Comment by ninjanomnom** [comment]
Or people could just not do that

**Comment by Jared-Fogle** [comment]
OOC and LOOC aren't synonymous? LOOC is usually used for instructing people on what to do in OOC terms (e.g. LOOC "click the metal in your hand").

**Comment by ninjanomnom** [comment]
For all proper uses of looc they are synonymous. You shouldn't be having ooc conversations in local space. You can ask for help in ooc just like looc.

**Comment by LetterN** [comment]
but imagine if someone said "how do i xeno?"

**Comment by ninjanomnom** [comment]
Then they ask a mentor

**Comment by LetterN** [comment]
so just, delete this entire file now?

**Comment by ninjanomnom** [comment]
Assuming nothing uses looc yeah that should be fine

**Comment by LetterN** [comment]
@ninjanomnom deleted

**Comment by ninjanomnom** [comment]
You don't need to mention me in prs I've commented in. Github has notifications for new commits in prs you're subscribed to.

On a basic search of the codebase there are other looc related pieces of code that should be removed along with this. `/client/verb/listen_looc()` for example.

**Comment by ninjanomnom** [comment]
The fuck, where is travis

**Comment by LetterN** [comment]
imagine travis, but it actually works this time

**Pull request closed without merging**
