### PR TITLE
Uncomments the thermite reaction

### PR DESCRIPTION
**Pull request by Anonmare**
I'm not sure why this was commented out but whatever

### CODE REVIEW

**Comment by Rohesie** [comment]
Due to balance concerns.

**Comment by spookydonut** [comment]
Are they? Were walls made thermite immune since the leak?

I'd support this if you added a limited supply ingredient or upped the amount of thermite you need to start the reaction.

**Comment by Rohesie** [comment]
I seem to have missed a little piece of code, they are not, only hulls.

The requests seem fair to me.

**Comment by Rohesie** [comment]
Add a rare and limited ingredient to the mix, like phoron, uranium or whatever.

**Comment by Anonmare** [comment]
I suppose I can make it require phoron

**Comment by Rohesie** [comment]
Cheap, but alright. Merging it, can be tweaked later.

**Pull request merged**
