### PR TITLE
Buffs Clowns

### PR DESCRIPTION
**Pull request by as334**
Clowns survivors can now slip xenos with their Banana peels.

**HONK!**

### CODE REVIEW

**Comment by Ghommie** [comment]
The override_noslip var is exclusively used for space lube. Currently xenomorphs are immune to prevent hilarious yet balance-wise broken death traps. Removing such immunity will throw in the meta for doctors and researchers to make lube grenades and sprays (which may work on non-floored turfs). And on LV there are already a pair of banana peels mapped in, and a stun of merely 4 seconds is still enough to freeze a t1-t2 with a decent firearm.

**Comment by as334** [comment]
Honestly I have no issues with a space lube meta

**Comment by Supermichael777** [comment]
>marine tries to use slips
Whole squad falls over and dies to solo runner leaping and slashing.

I can taste the salt from all the way over here!

**Comment by Rohesie** [comment]
No. Just no.

**Comment by ninjanomnom** [comment]
Making bananas ignore noslip is ridiculous but I'd be willing to entertain the idea of aliens slipping at a later date. Probably not all of them but having some of them slipable could be good.

**Pull request closed without merging**
