### PR TITLE
Quick revamp of adminhelp to make it easier to use for both players and admins

### PR DESCRIPTION
**Pull request by F-OS**
New adminhelp types:
"Rule Violation / Policy Question" - Sends to admins, not mentors.
"Gamebreaking Bug" - Sends to admins, special tools for bugfixes incoming, give suggestions?
"Gameplay Question" - Sends to mentors and admins.

### CODE REVIEW

**Comment by Qustinnus** [comment]
bugs should be reported to github not to admins because that will result in brainlets PMing me at 2am about them instead of making an issue on the gihtub

**Comment by Rohesie** [comment]
We don't have a developer administrative rank yet and this would require a larger rework of the system, besides hiding the initial AHelp from those without debug permissions.

**Comment by F-OS** [comment]
Yeah i'll just trash that

**Comment by Rohesie** [comment]
Outdated by #580

**Pull request closed without merging**
