### PR TITLE
Suicide PR 2.0, now without the restrictions and with useful admin notifications!

### PR DESCRIPTION
**Pull request by F-OS**
This PR re-implements suicide with a admin notification if you suicide as a important job.

### CODE REVIEW

**Comment by Wilchenx** [comment]
Letting people suicide while getting tacklespammed before infection is super fucking bad.

You can suicide anyway with a pistol to mouth/chest.

We don't need this and this will just break shit.

**Comment by F-OS** [comment]
@Wilchenx You can't suicide while stunned from what i can see.

**Comment by Rohesie** [comment]
I cannot see a single positive thing this adds to the game, and I can see a series of issues it causes:
* Harder for xenos to capture hosts, easier for them not to make it alive into the hive to be infected. Xenos already have the issue of being too slash-happy.
* Kind of much easier for people to die with a command away, blocking certain job slots that unlike in TG cannot really be replaced due to the skills they carry.
* A definite descent into the lower RP spectrum.

I love TG and have been playing it for half a decade. It has many good features CM could use. This is not one of them. It offers nothing besides "muh TG culture".

**Comment by Wilchenx** [comment]
@F-OS yeah but what if you break out of a stun for a second to pull this off


And why do we need this anyway if there's cryo and you can still suicide without a lazy verb.

**Comment by F-OS** [comment]
Based on some discord feedback I've added a delay to suicide. However, I do feel that this should be added because of some reasons I've elaborated on in discord.

**Comment by Wilchenx** [comment]
image

If thats the only reason for this then you can just close it and save some work for ninja

**Comment by F-OS** [comment]
@Wilchenx I have some other reasons, First of all, arbitrary restrictions on stuff like this is annoying and unneeded, along with that, you can already commit suicide in a multitude of ways so keeping this one way locked up behind a antagonist check makes absolutely no sense, and what you referenced there isn't even relevant as i realized the point Rohesie was making and added a time delay.

**Comment by Rohesie** [comment]
As far as I know it was intended to be higher RP than TG.
This is not an arbitrary restriction. It is a lack of an arbitrary feature. You _can_ suicide with a gun to the mouth (which is designed thinking of captured host/xeno interaction balance) and you can use other means of causing a lot of damage for yourself. And xenos have ways to counter that (the resin nest being a health stabilizer).
There is zero reason to add the feature of holding your breath to death, which as funny as that is in a TG context, is simply out of place here.

**Comment by F-OS** [comment]
This is overwhelmingly hated so until i get a opinion on this from rustled/mso that's a clear yes/no i'm closing this.

**Pull request closed without merging**
