### PR TITLE
Replacing Almayer walls with Bay walls

### PR DESCRIPTION
**Pull request by Arachnidnexus**
_Edit 5:_ Medical walls, hull walls, and corresponding windows now workable. EW reinforced windows need another pass as do the normal windows imo. Also just doing medical and hull walls/windows for now to conserve sanity.
image
image
image

First pass at exporting Bay wall sprites to DMCA. Currently this only touches almayer.dmi and walls.dmi in icons/turf but will hopefully include all other walls and also windows in the future. This is re-do of PR #487 with less messing up, hopefully.

_Edit 4:_ special decorative hull walls not done yet (light grey animated walls), windows are ehhhh WIP
image

_Edit3:_ minecraft walls, still a WIP after a failed attempt at zigzag pattern walls, no windows yet

_Edit2:_ a softer, gentler wall for a
image

_Edit:_ C U R V E D W A L L S (WIP)
image

### CODE REVIEW

**Comment by Qustinnus** [comment]
how is this with the windows

**Comment by Arachnidnexus** [comment]
It's not. This is mostly a placeholder for now until I can do windows + generic walls and then soften the look on the Bay wall corners too. Feel free to put a WIP or something so people can ignore it for now.

**Comment by Arachnidnexus** [comment]
Wait what

**Comment by Rohesie** [comment]
Looking good...

**Pull request merged**
