### PR TITLE
Adds a marine vendor for PFCs

### PR DESCRIPTION
**Pull request by F-OS**
Pros:
1. Reduces roundstart DMV simulator 2018
2. Allows for more varied gameplay.

Cons:
1. Slight buff.

### CODE REVIEW

**Comment by Rohesie** [comment]
Free mag harnesses might be an issue. The rest is fine, IMO.

**Comment by F-OS** [comment]
Fixed as per feedback.

**Comment by Rohesie** [comment]
Odd selection. Why these? These are not really the most common attachments by far.

**Comment by F-OS** [comment]
Mainly because i feel these attachments are able to be given out without balance issues.

**Comment by Rohesie** [comment]
Recoil compensator, angled grip, laser sight, gyro, bipod, any of the stocks and the mini-flamer all fit the same bill. Req never runs out of any of them.

**Comment by Rohesie** [comment]
In the clothes, what?

**Comment by F-OS** [comment]
It was the only thing that worked quickly and elegantly.

**Pull request merged**
