### PR TITLE
Clutter, now with 100% more drab olive greens

### PR DESCRIPTION
**Pull request by Arachnidnexus**
Replacing old clutter with new improved toe-stubbing clutter. Big crates were done using half of a tg crate sprite as a base while the barrels were a transformed then heavily modified oil drum (?) thing I found in tg objects.dmi. Little tactical cases were done by hand.

_Edit: wood crate sprite was moved to 'wood_crate_extra' because the secure crate needed to have its ropes cut in order to comply with how it acts right now in game._

CM:
image
DMCA:
image

_Dream Maker_
CM:
ship1
ship3
DMCA:
image
image

### CODE REVIEW

**Comment by Alterist** [comment]
hmm, i'm pretty sure the white box with straps becomes the white box without straps if you use a wirecutter on it, your sprites should reflect that too

**Comment by Arachnidnexus** [comment]
@Alterist AAAAAAAAAAAA-yeah you're right. I'll fix that

**Comment by Supermichael777** [comment]
Those barrels look kinda close to pillow shaded. brighten up one side and it might look better

**Comment by Arachnidnexus** [comment]
Gonna be honest, not sure what I broke or how I broke it.

**Pull request merged**
