### PR TITLE
Makes everything tg: Darkblue ui for lobbystuff

### PR DESCRIPTION
**Pull request by LetterN**
Next pr: highlander

### CODE REVIEW

**Comment by Borisvanmemes** [comment]
Highlander is in the code as-is.

**Comment by LetterN** [comment]
but the highlander they have is fucking l a m e

**Comment by MrStonedOne** [comment]
@LetterN travis

**Comment by ninjanomnom** [comment]
Testing webhook

**Comment by Rohesie** [comment]
Feel free to ask this to be re-opened when you resume working on it.

**Pull request closed without merging**
