### PR TITLE
QoL: Auto-Drop Items in Offhand When Wielding

### PR DESCRIPTION
**Pull request by Surrealaser**
Per title. QoL change.

### CODE REVIEW

**Comment by Surrealaser** [comment]
@iskyp What the problem is?

**Comment by mattroks101** [comment]
It should try to equip the item first, then drop it.

**Comment by Surrealaser** [comment]
@mattroks101 I considered it during my first draft; I'm not sure I'm into the idea of a panic wield involving an attempted careful placement prior to dropping, but it seems as though there are several people now who want this, so I'll add it.

**Comment by Surrealaser** [comment]
@factoryman942 Done.

**Pull request merged**
