### PR TITLE
buffs dancing

### PR DESCRIPTION
**Pull request by factoryman942**
Xenos can now move while using *dance

### CODE REVIEW

**Comment by Rohesie** [comment]
Yes, that is a balance concern. I intend to remove moonwalking already.

**Comment by Arachnidnexus** [comment]
Could prevent the crest randomness by dropping armor when dancing if that's a concern.

**Comment by Ghommie** [comment]
well, the directional crest shielding thing is located at projectile.dm, line 604.
A simple solution would be making the conditional on a var, said var set on TRUE on the two castes, and have it set on FALSE for the duration of the dance.

**Comment by Rohesie** [comment]
Seems a little convoluted for a meme, don't you think?

**Comment by factoryman942** [comment]
jesus christ this was a two line change I didn't want to have to actually do stuff

**Comment by factoryman942** [comment]
Just because I didn't want to doesn't mean I won't now
although it does require me knowing what to do about it

**Comment by factoryman942** [comment]
that hurts @Rohesie

**Pull request closed without merging**
