### PR TITLE
Makes everything tg: Hotkeys & buttons edition

### PR DESCRIPTION
**Pull request by LetterN**
after this: makes all normal lameui to greyui (the typical tg ui (not tgui))
now you can ""accidentally"" ick in ocky when using hotkeys

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Could you re-add the thing to make the text bar white when hotkey mode is enabled. it was a really helpful visual cue.

**Comment by subject217** [comment]
Also, no resist hotkey? It's bound to B on /tg/.

**Comment by Rohesie** [comment]
Once the author addresses these requests, either denying or accepting them and making the changes, I'm merging this. It has been tested and works as intended.

**Comment by subject217** [comment]
If LetterN doesn't want to do it I'll open a PR with that and probably some other binds too.

**Comment by Rohesie** [comment]
The PR has been tested and approved by the players through in-game vote. Further modifications can be made in a new PR. This is accepted.

**Pull request merged**
