### PR TITLE
"That's a big prison wall." "4 YOU!" (prison walls/windows/frames)

### PR DESCRIPTION
**Pull request by Arachnidnexus**
Okay so the cell windows are magically and are either indestructible or allow bullets to phase through them, but I blame that on mapping and variables. Also they're missing window frames so yeah....

_Edit:_ fixed stripe mismatching, ping me on discord if you spot something i missed
_Edit 2:_ softened up the look of the support things on the reinforced walls a bit more

reinforced prison walls and normal prison walls (based off of metal and reinforced walls):
image

reinforced prison windows:
image

cell windows and such
image

### CODE REVIEW

**Comment by Alterist** [comment]
48106786-93a9f080-e202-11e8-81e8-76e203366379
this part looks a bit weird, the vertical wall's red stripe also looks like it's very curvy when it should probably be mostly straight, perhaps you can fix both problems with one change?

**Comment by Arachnidnexus** [comment]
@Alterist the alignment was offf AAAAAA but yeah good point. I updated the walls. How's this look now? 
image

**Comment by Alterist** [comment]
Much better, ready for merging?

**Comment by Arachnidnexus** [comment]
Yeah, sounds good.

**Pull request merged**
