### PR TITLE
Logging port

### LINKED ISSUE #155: Logging is terrible!
You access one single log for all logging types, you can't access logs for individual players, and the logging is grouped per-day rather than per-round. On top of that, in-game, you cannot access logs past the current day.

Our logging tools should be ported.
@rustledjimm 
@francinum

### PR DESCRIPTION
**Pull request by JJRcop**
This ports the /tg/station logging system, including the new refactor. Each player has individual logs, logs are separated per-round rather than per-day.

This should look familiar

Closes #155

### CODE REVIEW

**Comment by Iatots** [comment]
Does it fix #24 and #155 ?

**Comment by JJRcop** [comment]
It doesn't fix #24 but it does fix #155. #24 should be simple to fix

**Comment by francinum** [comment]
#24's core issue is attack logs being turned on for admins by default.

**Comment by JJRcop** [comment]
By the way, I didn't port everything, like for example tcomms logs, just most things

**Comment by Rohesie** [comment]
This has been testmerged and worked fine.
I haven't seen any glaring issues with the code, so after @ninjanomnom gives the green light this will be merged.

**Comment by JJRcop** [comment]
After a few days i'm going to do another ```world.log <<``` pass to catch any new changes.

**Pull request merged**
