### PR TITLE
Makes Human Medic Voicelines More Consisent

### PR DESCRIPTION
**Pull request by chesse20**
[:cl:]
Makes human male medic voice lines more consisent
/[:cl:]
Lol check out my pr

### CODE REVIEW

**Comment by Wilchenx** [comment]
Can't even play the sound in my browser to know what it is

image

what the fuck did you do here

**Comment by chesse20** [comment]
its a issue with github, just download the ogg file and it will work

**Comment by Wilchenx** [comment]
Anyway are you sure that heavy from tf2 medic call is free to use in open source project?

**Comment by chesse20** [comment]
theres already a tf2 medic call in the code, i assume the colonial marines devs got permission with that one too

**Comment by ninjanomnom** [comment]
We haven't gotten permission and I doubt CM did as well. Let's not have obviously copywritten content thanks.

**Pull request closed without merging**
