### PR TITLE
Fixes jobs list not populating

### PR DESCRIPTION
**Pull request by JamesDenholm**
Unfortunately @LetterN isn't descriptive in their commits so I don't know what the intent of the commit was, BUT it does fix the jobs list not populating

(Yeeeee N I'mma call you out come at me, fight me bro)

But yeah Ninja you're gonna want to test this more because while it works for Extended and Distress Call, idk enough about adminning to be able to work out the full ramifications here

### CODE REVIEW

**Comment by JamesDenholm** [comment]
I joke, though, N.

To be clear.

**Comment by ninjanomnom** [comment]
Nah I don't need to test this sort of thing, the structure shouldn't have fundamentally changed from the first commit other than the change to subtypesof and this changes the code back to how it was just with the relative pathing fixed.

**Comment by JamesDenholm** [comment]
gosh DANGIT ninja

**Comment by LetterN** [comment]
i hate the tab key

**Pull request merged**
