### PR TITLE
Removes "phoron"

### LINKED ISSUE #134: it's plasma, not phoron

### PR DESCRIPTION
**Pull request by kachnov**
closes #134

### CODE REVIEW

**Comment by ninjanomnom** [comment]
I've always hated the name plasma honestly

**Comment by Jared-Fogle** [comment]
@ninjanomnom Logistically, phoron does make more sense than plasma. However, plasma is far too ingrained for anyone to want to switch.

👍

**Comment by ninjanomnom** [comment]
There's no hill to die on yet, I'm bulldozing it.

We can come back to this later perhaps.

**Comment by kachnov** [comment]
how wude

**Pull request closed without merging**
