### PR TITLE
The pyro spec no longer gets fucked by angry tackle-spam xenos dragging him into his own fire.

### PR DESCRIPTION
**Pull request by F-OS**
Title.

Pros: Removes a infuriating meta

Cons: Fucks with the general balance and skill floor for pyro specs.

### CODE REVIEW

**Comment by Surrealaser** [comment]
@F-OS If this makes him immune to fire, this is long overdue, and I approve.

**Comment by Supermichael777** [comment]
So even more reason for the brainlet pyro main to stand in the back and torch his own squad

**Comment by Rohesie** [comment]
We'll have to test this and tweak how much burn damage they get. It's fine that they don't get set on fire, but we don't want them to be 100% immune to fire through kelo+derm+tram, for example.

**Comment by Surrealaser** [comment]
@Rohesie They should be basically immune to fire; nothing wrong with that.

**Comment by Rohesie** [comment]
They have the best armor in the game second only to B18. Total fire immunity might be a bit too much.

**Pull request merged**
