### PR TITLE
Remove mention of NSDAP

### PR DESCRIPTION
**Pull request by Wilchenx**

### CODE REVIEW

**Comment by F-OS** [comment]
Nazism is bad feel bad

**Comment by CitrusGender** [comment]
pls

**Comment by Tlaltecuhtli** [comment]
here comes the 5th reich

**Comment by Wilchenx** [comment]
shooting nazi antags is a good thing tho

**Comment by subject217** [comment]
IIRC, the ban on Nazi content is because of German laws, and it could be blocked in Germany otherwise.

**Pull request closed without merging**
