### PR TITLE
Call me maybe (Replacing telecomms & tower sprites)

### PR DESCRIPTION
**Pull request by Arachnidnexus**
Replacing telecomms on the ship with TG sprites. Plan is to replace telecomms tower with new sprites as well. _Edit: check out the tower ayyyyyy_

CM:
image
image

DCMA (like all TG really):
image
image

CM:
image
DMCA:
image
DMCA (vision):
image

### CODE REVIEW

**Comment by Arachnidnexus** [comment]
Actual new comm tower:

image
It blinks, it spins, it turns.

I added 1 more frame so blame me if performance drops tremendously on ice rounds.

**Comment by Arachnidnexus** [comment]
image
Update on tower where I can't find a good way of making the top dish look good.mp4

**Comment by francinum** [comment]
Can you update your OP with the new icon?

**Comment by Arachnidnexus** [comment]
@francinum updated it, it has one more animation frame than the original.

**Pull request merged**
