### PR TITLE
mapmerge2 + converts maps + adds mapmerge shit to .gitignore

### PR DESCRIPTION
**Pull request by praisenarsie**
thanks to @spacemaniac for writing mapmerge2

someone should port the .gitignore from tgstation

### CODE REVIEW

**Comment by praisenarsie** [comment]
don't understand the issue

**Comment by SpaceManiac** [comment]
Double-check that the maps still open in Dream Maker after being stored as TGM. If they crash they have too many lines in them for BYOND to handle (yes, it's actually based on line count) and will need to be stored non-TGM. It's possible to edit the mapmerge script to output non-TGM files to get a medium between messy maps and too-large maps.

**Comment by praisenarsie** [comment]
looks like the almayo was 2big

**Comment by Jalleo** [comment]
can you also get the other maps in the repo able to be loaded as well? 
They need some path changes. Some small others larger.

(If we get asked to remove em we can do so)

**Comment by Rohesie** [comment]
Is there still interest here?

**Comment by ninjanomnom** [comment]
Aparently not

**Pull request closed without merging**
