### PR TITLE
Dust Raider Sprite Swapover

### PR DESCRIPTION
**Pull request by sleepyretard**
Swaps Command and Enlisted personnel uniforms over to the d_ variants. Excluding weapons, and certain other uniforms (Pilot Officer) given discrepancies or lack of proper spriting

### CODE REVIEW

**Comment by Rohesie** [comment]
@Ghommie and @Alterist , care to review?

**Comment by Ghommie** [comment]
Opinions aside, a first glance on the IconsDiffBot's report doesn't show anything amiss, but it's always better to wait and doublecheck. I appreciate how the former sprites weren't just simply removed and instead put on a "m_" list.

**Comment by Alterist** [comment]
I have no strong feelings one way or the other. You might need to create sprites for the missing roles for consistency tho

**Comment by Rohesie** [comment]
This has been approved both in-game and in discord voting. Since both of the main sprite contributors have nothing against it, I'm merging it.

**Pull request merged**
