### PR TITLE
Adds hypervene autoinjector, to lifesaver belt

### PR DESCRIPTION
**Pull request by JamesDenholm**
Obviously this won't work until the hypervene PR is accepted -- DNM while #169 is outstanding.

TL,DR adds a 10u hypervene autoinjector to the lifesaver belt, for when you get the urge-to-purge, on the go.

### CODE REVIEW

**Comment by JamesDenholm** [comment]
Given Sur collapsed his PRs into one, 169 is gone -- this depends on #181 -- but it's less useful given 181 also adds a hypervene pill bottle to medic belts. The autoinjector is intended as an alternative to that addition, given a pill bottle is probably overkill for such a niche purge chemical.

**Comment by JamesDenholm** [comment]
Also, added to medic vendor as a 2-cost, and five to the medical vending machine.

**Comment by ninjanomnom** [comment]
I'm unsure about more marine buffs for the moment but I'd be fine having this up for discussion if not for it being based on code that isn't merged yet. There's no need to queue prs ahead of time, be patient.

**Comment by JamesDenholm** [comment]
It wasn't queued, it was accompanying Sur's set of PRs.

**Comment by ninjanomnom** [comment]
They aren't/weren't merged yet. Having a pr waiting specifically for another pr is queuing.

**Pull request closed without merging**
