### PR TITLE
Mat13295: Ice is Aliens lose hosts after marines get hugged cause lmao muh frozen iceball shithole (NO LONGER)

### PR DESCRIPTION
**Pull request by F-OS**
This makes facehuggers act as thermal protection for marines so they don't die in nests after getting hugged. Also to allow for this, facehuggers wait a bit before falling off.

### CODE REVIEW

**Comment by JamesDenholm** [comment]
Obligatory "facehuggers fall off" comment goes here

**Comment by Kingtrin** [comment]
Facehuggers would need to be changed so that they stay on for this to work. Other solutions could be nests providing heat protection, or toning down the cold damage in ice colony.

**Comment by Iatots** [comment]
Did you check nest code? They already stabilize people and I've never had a problem on CM with hosts on ice.

**Comment by F-OS** [comment]
Nests don't stabilize. https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/blob/2e732561057a5810402c4f811910cfaf507ac4d3/code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm

**Comment by Iatots** [comment]
This is bizarre, I am decent at gauging deadly wounds and so are others. It could be in another file, heck if I know. Would you be willing to test it out on a server? My potato can't handle this codebase.

**Comment by ninjanomnom** [comment]
The nest handling this is the better option not the hugger

**Comment by chesse20** [comment]
isn't this balanced already by how awful it is to play on ice colony as a marine

**Comment by ninjanomnom** [comment]
Aliens do need some buffs anyway after recent changes so I wouldn't mind fixing this even if this were a balance decision

**Comment by JamesDenholm** [comment]
Ballsy alternative idea -- What if _alien embryos_ slowly healed up marines? Maybe not if they're "too far gone", but it'd kind of make sense if the parasite did what it could to ensure the host lived until super happy fun goretime.

**Comment by ninjanomnom** [comment]
If it's minor enough that sounds fine

**Comment by Iatots** [comment]
Nah they  should start munching on organs once they are developed enough to survive the host dying.

**Comment by FantasticFwoosh** [comment]
``Nah they should start munching on organs once they are developed enough to survive the host dying.``

But sopa marinha would taste better reheated, i mean just for the time being. Maybe being in critical and embyro laiden puts you under stasis (similar to /tg/ medical equipment code) that prevents further cold damage until the embryo is through with you with the eventual burst killing you outright.

You already have stasis bags on this codebase @Iatots , im sure you could find something to do with it.

**Comment by F-OS** [comment]
Forgot about this PR, can someone summarize the needed changes for it?

**Comment by Rohesie** [comment]
The suggestion is for giving the nests a temperature stabilization/isolation property, not the facehuggers themselves.

**Comment by F-OS** [comment]
Alright, i'll make a new branch and do that, thanks!

**Pull request closed without merging**
