### PR TITLE
Almayer Edit

### PR DESCRIPTION
**Pull request by Alterist**
Code Side changes:
Adds TG bar signs, change them with a multitool
Removes Almayer stencil, replaced with a DMCA stencil
Moves OB and AA cannon sprites from icons/effects/128x128.dmi to icons/obj/machines/artillery.dmi
Moves athletic lockers from almayer props to where they should be
Delets several non-functional Almayer props from code and map
Removes WY reference from ATM
Adds Extra Combat Shotgun into armory gun cabinets, instead of placing them on the map
Adds Extra Riot shield into Sec Riot gear ,instead of placing them on the map
Adds Webbing into Cargo Locker Spawn, instead of placing them on the map
Adds Webbing and Officer Armor to RO locker
Gives Freezers a proper parent sprite

### CODE REVIEW

**Comment by Alterist** [comment]
**DMCA-Class Marine Cruiser Air-capable ship Flight II Commander's Handbook**

colonialmarinesalpha 2018-09-26 210411
If you're reading this, then you have been assigned to a Flight II of one of our Nanotrasen-built, state of the art DMCA class vessels. This handbook will guide you to the differences between this vessel and the Flight I's you have been stationed aboard.

colonialmarinesalpha 2018-09-26 210347

Lets begin with the room you will stay in for most of your time, the Commander's Quarters. As you can see , it's size have been somewhat reduced, this is due to reports the Commander's belonging being damaged during ship to ship combat. The reduced profile means there is a lesser chance of it being hit. We have redesigned the office's layout after feedback from multiple commanders, adding a private study for the Commander, which includes a display case for any cherished belongings.

colonialmarinesalpha 2018-09-26 210411

The Ship's name is proudly stenciled on the port of the ship, pictured here is the lead ship of the DMCA class

colonialmarinesalpha 2018-09-26 210438

We have added a pool to the upper deck to promote health and well-being of the ship's crew, remember, no running around the pool now!

colonialmarinesalpha 2018-09-26 210452

To accommodate the the flow of personnel to briefing, we have widened the officer's door 

colonialmarinesalpha 2018-09-26 210555

The cargo elevator on on the port side of CIC have also been relocated to reduce the size of the upper deck. This reduction and that of the commander's quarters gives the Flight II a reduced radar cross section compared to the Flight I's.

colonialmarinesalpha 2018-09-26 212823

Now let's move on to the lower deck, this is where the majority of the improvements have been made

colonialmarinesalpha 2018-09-26 210610

The flanges were found to be completely useless after analyzing combat data from past engagements. As such they have been removed.

colonialmarinesalpha 2018-09-26 210726

The entire vehicle deck have been removed after audits revealed that building an entirely separate deck just to house a single tank was prohibitively expensive. The Tank Crew's quarters have been moved to what was previously the storage room. 

colonialmarinesalpha 2018-09-26 210730

The Tank Garage have been moved to just besides the Tank Crew's quarters. This should improve combat response time by 50%

colonialmarinesalpha 2018-09-26 210741

The Pilots workshop remains mostly unchanged, simply widened a bit to allow for easier access to dropship equipment

colonialmarinesalpha 2018-09-26 210747

The Pilot's quarters have been merged with their office, this should also improve pilot response time by 25% and construction costs by 10%

colonialmarinesalpha 2018-09-26 210759
In order to fulfill the mission requirements of a Extended Range, Long Term, Defense of Mining Colony and Antiterrorism Operations Ship, an expanded kitchen/bar and hydroponics suite have been added to the ship. Now marines can enjoy fresh produce, even in the depths of space!

colonialmarinesalpha 2018-09-26 211109

Docking ports for supply ships have been integrated into the hull, improving the ship's radar profile, aerodynamics and structural integrity, it's also much much cheaper than building shutters out of adamantium

colonialmarinesalpha 2018-09-26 211112
 
We've added additional Food dispensers, so those marines hungry from cryosleep can get their food quicker

colonialmarinesalpha 2018-09-26 211212

Waste gas ejection system redesigned, making each DMCA-Class ship 5 credits cheaper to build without any significant impact to the ship's combat capabilities. Not pictured is a general improvement to the electrical and waste disposal systems on the ship, removing many redundant wiring or pipes

colonialmarinesalpha 2018-09-26 212710

the many cost-saving modifications made to the Flight II's have been mentioned in this handbook, but many of those savings have been used to improve the living quality of marines on board. Nowhere is this more obvious than the Recreation Center, which features a basketball court, arcade and boxing ring. Designed to allow marines to exercise and work off combat related stress, which studies suggest reduces the occurrence of mutinies onboard Combat Ships.

This concludes the DMCA-Class Marine Cruiser Air-capable ship Flight II Commander's Handbook. We hope the improvements can allow you to lead marines to secure a brighter future for Humanity and Nanotrasen.

**Comment by F-OS** [comment]
how do i upvote a pr twice

**Comment by chesse20** [comment]
press click on the merge button

**Comment by Rohesie** [comment]
Adds TG bar signs, change them with a multitool
Removes Almayer stencil, replaced with a DMCA stencil
Moves OB and AA cannon sprites from icons/effects/128x128.dmi to icons/obj/machines/artillery.dmi
Moves athletic lockers from almayer props to where they should be
Delets several non-functional Almayer props from code and map
Removes WY reference from ATM
Adds Extra Combat Shotgun into armory gun cabinets, instead of placing them on the map
Adds Extra Riot shield into Sec Riot gear ,instead of placing them on the map
Adds Webbing into Cargo Locker Spawn, instead of placing them on the map
Adds Webbing and Officer Armor to RO locker
Gives Freezers a proper parent sprite

**Pull request merged**
