### PR TITLE
End Tofu Racism

### PR DESCRIPTION
**Pull request by JamesDenholm**
Someone pointed out on discord that tofu only gives ~1/5th nutriment of other meals, so this happened

Tofu, Then And Now

Notably, I can't sprite for shit, but hey if someone else has a better idea for how to represent large white cubes I'm all ears.

### CODE REVIEW

**Comment by Soundwavesghost** [comment]
haha Come on it shouldn't be 10 maybe 7. Its a meme that its not good as real meat so have it be relevant but just not as good as 'real' meat.

reagents.add_reagent("nutriment", 7)

**Comment by JamesDenholm** [comment]
Eh, I tried to make the downside that it takes longer to chow through. If it makes you feel better, let's just say it's a BIG lump of tofu.

**Comment by JamesDenholm** [comment]
BIG blocks of tofu, ninja

Tofu the size of your fist

Think about it

**Comment by Anonmare** [comment]
Tofu: A meal created by people who believe in a galaxy where soldiers kill people, not animals.

**Comment by ninjanomnom** [comment]
I already did think about it. I eat a lot of tofu (and meat) in real life. It really is easier to eat.

**Comment by ninjanomnom** [comment]
Went with #103 instead for tofu changes

**Comment by JamesDenholm** [comment]
Better sprites tbh

**Pull request closed without merging**
