### PR TITLE
Tank Tweak (Runs over more objects)

### PR DESCRIPTION
**Pull request by Suicidalpickles**
allows the tank to run over:

-disposal units
-security camera consoles
-sec record consoles
-hydro trays

### CODE REVIEW

**Comment by Surrealaser** [comment]
I like it, though I would have it add random debris as well, like metal rods, glass, robogibs and so on

**Comment by Rohesie** [comment]
`Dispose()` is definitely not the right proc.

**Comment by Suicidalpickles** [comment]
couldn't figure out how to get it running with a destroy proc in place of the dispose proc, kept coming up as undefined.
tldr im terribad

**Comment by Rohesie** [comment]
You'll want something like:
```
new /obj/item/stack/sheet/metal(S.loc, 2)
cdel(S)
```
Though I'd wait for Stoned's MC port, and then do `qdel(S)` instead.

**Comment by Rohesie** [comment]
Now that'd be ideal, but a bit beyond what Suicidalpickles can do.

**Pull request closed without merging**
